spring.application.name=member-connect-backend
# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/member_connect_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always

aws.accessKey=REDACTED_AWS_ACCESS_KEY
aws.secretKey=REDACTED_AWS_SECRET_KEY
aws.region=ap-south-1
aws.bucketName=memberconnect-documents