spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.error.include-message=always

# AWS
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucketName=${AWS_BUCKET_NAME}

# Scholarship
scholarship.required.remitted.months=12
scholarship.lookback.years=1
university.scholarship.minor.required.amount=500
university.scholarship.minor.required.months=120
university.scholarship.minor.multiplier.percent=150
