package com.memberconnect.backend.enums;

public enum MemberStatus {
    ACTIVE,
    RETIREMENT_REQUESTED,
    RETIREMENT_APPROVED,
    TERMINATION_REQUESTED,
    RETIRED,
    INACTIVE,
    RESIGNED,
    TERMINATED,
    DECEASED,
    MEMBER_DEATH_RECORDED,
    SELECTED_FOR_DORMANT,
    SENT_FOR_DORMANT_APPROVAL,
    INACTIVE_DORMANT
}