package com.memberconnect.backend.enums;

public enum UniversityScholarshipRequestStatus {
    NEW,
    INCOMPLETE,
    SUBMITTED_FOR_COMMITTEE_APPROVAL,
    SUBMITTED_FOR_NORMAL_BOARD_APPROVAL,
    SUBMITTED_FOR_DEVIATION_BOARD_APPROVAL,
    ADDED_TO_NORMAL_BOARD_APPROVAL_LIST,
    ADDED_TO_DEVIATION_BOARD_APPROVAL_LIST,
    APPROVED,
    REJECTED,
    INACTIVE
}

