package com.memberconnect.backend.model;

import java.math.BigDecimal;

/**
 * The slice of state a Death Donation entitlement calculation reads and writes.
 *
 * Two unrelated records carry a death donation entitlement:
 *
 *   MemberDeathRecord     - Requirement 04 (MMT18-MMT25), the death of the
 *                           Member themselves
 *   DeathDonationRequest  - Requirement 05 (MMD01-MMD08), a donation the Member
 *                           claims for a deceased relative
 *
 * The arithmetic in {@code DeathDonationEntitlementService} is identical for
 * both, so it operates on this interface rather than being duplicated. Every
 * accessor below is already generated by Lombok on both entities; the interface
 * exists to name them, not to add behaviour.
 *
 * Deliberately narrow: it exposes only the entitlement figures and the member
 * the calculation needs, so implementing it does not drag one requirement's
 * concerns into the other's entity.
 */
public interface DonationEntitlementTarget {

    /** The member the entitlement belongs to; used to query the Finance Module. */
    Member getMember();

    // ---- Operator-editable inputs, each with its "was edited by hand" flag ----

    Integer getMonthsRemitted();

    void setMonthsRemitted(Integer monthsRemitted);

    Boolean getMonthsRemittedEdited();

    void setMonthsRemittedEdited(Boolean edited);

    BigDecimal getReceivedPast12Months();

    void setReceivedPast12Months(BigDecimal receivedPast12Months);

    Boolean getReceivedPast12MonthsEdited();

    void setReceivedPast12MonthsEdited(Boolean edited);

    BigDecimal getCreditedToSpecialFixedAccount();

    void setCreditedToSpecialFixedAccount(BigDecimal creditedToSpecialFixedAccount);

    Boolean getCreditedToSpecialFixedEdited();

    void setCreditedToSpecialFixedEdited(Boolean edited);

    // ---- Finance-owned figures ----

    String getFuneralAccountNo();

    void setFuneralAccountNo(String funeralAccountNo);

    BigDecimal getFuneralAccountCredited();

    void setFuneralAccountCredited(BigDecimal funeralAccountCredited);

    BigDecimal getFuneralAccountMaximum();

    void setFuneralAccountMaximum(BigDecimal funeralAccountMaximum);

    // ---- Derived figures ----

    BigDecimal getMaximumDonationAmount();

    void setMaximumDonationAmount(BigDecimal maximumDonationAmount);

    BigDecimal getEligibleDonationAmount();

    void setEligibleDonationAmount(BigDecimal eligibleDonationAmount);

    BigDecimal getDisburseDonationAmount();

    void setDisburseDonationAmount(BigDecimal disburseDonationAmount);

    BigDecimal getDonationMultiplierApplied();

    void setDonationMultiplierApplied(BigDecimal donationMultiplierApplied);

    /**
     * Cause of death, when the record has one. Requirement 04 lets a configured
     * Cause of Death override the general maximum; Requirement 05 has no such
     * concept (SRS 2.2.3 takes the maximum from configuration outright), so
     * DeathDonationRequest returns null and the override branch is skipped.
     */
    String getCauseOfDeath();

    /**
     * Legacy single-amount column, kept in step with the payable figure so
     * anything still reading it does not see a stale hand-typed number.
     * Only MemberDeathRecord has one; for everything else this is a no-op.
     */
    default void setDeathDonationAmount(BigDecimal deathDonationAmount) {
        // No legacy column to mirror.
    }
}
